version: "2"

services:
  app:
    build: .
    container_name: rcmltb
    command: bash start.sh
    volumes:
      - /usr/src/app/downloads:/usr/src/app/downloads:rw # optional
    ports:
      - "83:83" # qbittorrent selection webserver
      - "81:81" # local mirror files webserver
      - "8181:8181" # rclone serve index webserver
    restart: on-failure
      
      
